### ISSUE TITLE
Tailscale Routing Not Working?

### ISSUE THREAD

**Issue by AKPWebDesign** [MinisculeGirraffe/Tailscale-UDMPro#2]
I've set this up to the best of my abilities, but no matter what I do, I can't seem to get devices on my Unifi network to be able to reach devices on my Tailscale network. I've ensured that the UDM Pro is able to ping the `tailscaled` container, which works just fine. I've also ensured that the `tailscaled` container can ping devices on both networks (Unifi and Tailscale), which also works fine.

I imagine something is going wrong with forwarding through the container, but I'm not sure what that could be, since everything I've read indicates that the forwarding part should just work.

Any assistance you can provide would be greatly appreciated!

**Comment by MinisculeGirraffe** [comment]
Heya. It's like midnight right now for me, but I can take a look tomorrow when I get off work. Feel free to drop me your logs(tailscale, start script, route table, CNI Config, etc) and I can probably tell ya what's wrong.

**Comment by MinisculeGirraffe** [comment]
My wild guess is that it's something in the CNI config or startup script that wasn't edited to be unique to your router, but it's kinda a who knows situation.

FWIW everyone i've talked to has gotten a working setup using this method(me included but that's kinda biased lmao), so it definitely works. Might be something specific to your env.

**Comment by AKPWebDesign** [comment]
> It's like midnight right now for me

No worries, it was also like midnight for me when I put in the issue haha. 

I'm sure it's just something I've missed or am doing wrong... I should probably note that I've taken your configs here and just stripped out anything IPv6-related, as I can't get IPv6 working on my network in the first place. It's possible that that's the reason Tailscale isn't working, but I hope that isn't it.

I took a look at the tailscale container logs and don't see any errors there, that part seems to be running smoothly. I can get the logs to you but it's kind of a pain. Here's the rest though:

Start script:
```
#!/bin/sh

#configuration variables:
#The VLAN the tailscale container will be attached to.
VLAN=0

#The IPv4 address of the tailscale container.
IPV4_IP="192.168.10.10" # is this supposed to be an IP on my existing network? I did try that way too, using something on my network and the appropriate gateway but it didn't seem to make a difference
IPV4_GW="192.168.10.1/24"

#The local routes you want to expose to tailscale
#Seperate with a "," for multiple routes
SUBNET_ROUTES="10.69.0.0/17"

#The tailscale ipv4 subnet is static to the CGNAT range
#https://tailscale.com/kb/1015/100.x-addresses/
TAILSCALE_NETV4="100.64.0.0/10"

# set VLAN bridge promiscuous
ip link set br${VLAN} promisc on

# create macvlan bridge and add IPv4 IP
ip link add br${VLAN}.mac link br${VLAN} type macvlan mode bridge
ip addr add ${IPV4_GW} dev br${VLAN}.mac noprefixroute

# set macvlan bridge promiscuous and bring it up
ip link set br${VLAN}.mac promisc on
ip link set br${VLAN}.mac up

# Add routes to container through macvlan bridge
ip route add ${IPV4_IP}/32 dev br${VLAN}.mac

# Add Tailscale IP Routes via Container IP
ip route add ${TAILSCALE_NETV4} via ${IPV4_IP} dev br${VLAN}.mac

#Start Container
docker start tailscaled
#Enable IPv6 routing on container
docker exec tailscaled sysctl -w net.ipv6.conf.all.forwarding=1
#Enable the VPN
docker exec tailscaled tailscale up --ssh --advertise-exit-node --hostname=UDM-Pro --accept-routes=true --advertise-routes=${SUBNET_ROUTES}
```

CNI config:
```
{
  "cniVersion": "0.4.0",
  "name": "tailscale",
  "plugins": [
    {
      "type": "macvlan",
      "mode": "bridge",
      "master": "br0",
      "mac": "00:1c:b4:44:3d:f2", # this is just a made up MAC address... is that the right way to do it?
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.10.10/24",
            "gateway": "192.168.10.1"
          }
        ],
        "routes": [
          {
            "dst": "0.0.0.0/0"
          }
        ]
      }
    }
  ]
}
```

Route table:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         173-15-204-58-B 0.0.0.0         UG    0      0        0 eth8
10.69.0.0       *               255.255.128.0   U     0      0        0 br0
100.64.0.0      192.168.10.10   255.192.0.0     UG    0      0        0 br0.mac
173.15.204.56   *               255.255.255.252 U     0      0        0 eth8
192.168.10.10   *               255.255.255.255 UH    0      0        0 br0.mac
```

**Comment by MinisculeGirraffe** [comment]
The idea behind this setup is that tailscale doesn't play well with the default Unifi network configuration. There's all sorts of modifications related to routing,dns,iptables, etc that Tailscale needs to perform to establish a vpn tunnel. When you bind it to the public IP address of the router it doesn't work for like at least 3 reasons I never fully cared to track down or troubleshoot.  

I still think it should be possible, but all of the other solutions i've found that tried to do this ended up not working, or being unreliable for one reason or another.  So the easiest solution to that being that you just don't try and run tailscale on the routers public IP at all. Since local network devices can use tailscale just fine, you have the container pretend to be a device on the local network. 

The CNI configuration along with the startup script is what allows this to happen. The IPv6 stuff is the exact same concept and should be totally optional. 


To give an example of how the traffic is supposed to flow, if my laptop needed to talk to some other device in the tailnet without being connected to tailscale, the general network path would be 

My laptop -> UDM -> Tailscale container -> Tailnet -> Tailscale device. 

Tailnet being a stand in for the wireguard tunnel between the tailscale container and the public endpoint of the other tailscale device. But that's not super relevant for our purposes. 

To break this down in more detail

- My laptop (`192.168.10.50`) needs to talk to some tailscale device at (`100.98.143.115`). My laptop knows that any non local traffic(I.E anything that's not `192.168.10.0/24`) needs to be sent to the UDM (`192.168.10.1`). This happens via the default `0.0.0.0/0` route configured on my laptop. My laptop has no idea how to talk to the tailscale device, only that anything it doesn't know about gets sent to the UDM. 

- From the UDM's perspective at this point, it's just received traffic on (`192.168.10.1`) from my laptop (`192.168.10.50`) that needs to go to Tailscale Device (`100.98.143.115`).  The UDM also has no idea how to talk to this tailscale device.  But, the start up script should have configure the routing table to send all tailscale traffic (`10.64.0.0/10`) to a single address, the container (`192.168.10.10/32`), and that address will know what to do next.  You can see this in the following line of your route table.
```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
100.64.0.0      192.168.10.10   255.192.0.0     UG    0      0        0 br0.mac
```

- From the container perspective, it's just received traffic on its network interface `192.168.10.10` from my laptop(`192.168.10.50`). The container knows how to talk to my laptop (`192.168.10.50`) through  the UDM (`192.168.10.1`). But the container also knows how to talk to `100.98.143.115` due to routes configured by the tailscale daemon running inside it.  It completes the connection, and then sends the traffic back to the UDM. which sends it back to my laptop.

Thus my laptop is able to speak transparently with a tailscale device while on my local network, despite not being connected to tailscale locally. 



Now, as to why your config isn't working.  What I think Is going on, is that the CNI config is referencing an incorrect subnet that isn't configured in your router.  This is probably a foot gun I could have explained better. 

The address, gateway, and subnet that you enter in for this value have to be valid for the configuration values of your device. Based on your route table you posted it looks like br0 is assigned the subnet `10.69.0.0/17`. Therefore the tailscale container would have to be within this value if that interface was being used, and point to whatever IP the gateway is listening at(probably `10.69.0.1` but idk you might have it at something else).

If you don't want the container listening in this subnet, and want to keep it in the `192.168.10.0/24` range, that's also possible, but you would need to configure the UDM through the GUI to listen to that address range on a VLAN, and update the interface in the configs to point to the br<VLAN ID> interface doing that would have created. 

Now as for your questions

> this is just a made up MAC address... is that the right way to do it?

Pretty much, the important part is that it's unique on your local network. The chances of a conflict are pretty low though so this isn't like a huge concern, just an extremely unlikely foot gun.

> IPV4_IP="192.168.10.10" 
> is this supposed to be an IP on my existing network? I did try that way too, using something on my network and the appropriate gateway but it didn't seem to make a difference

Yup. It's supposed to be an IP on your existing network, and also match the CNI configuration exactly. 



Final note:

If you're not using ipv6 you're safe to remove this line.  It's not really hurting anything by including it, but your container doesn't need to route ipv6 if you're not using it.
```
#Enable IPv6 routing on container
docker exec tailscaled sysctl -w net.ipv6.conf.all.forwarding=1
```

When attempting to troubleshoot the tailscale containers connection here's typically the path I would take

- From the UDM Pro, ping the tailscale containers IP. If no response you've fucked up the CNI config or the interface configuration in the startup script

- From the container, ping the UDM Pro. This should always work if the previous step works. If it doesn't you've fucked up the same things as above.

- Validate the Tailscale daemon is running inside of the container, and that it's successfully connected. If it's not you've likely fucked up the filesystem mounts when creating the container. Do a docker rm on the container and try again. 

- From within the tailscale container, attempt to ping a device inside of the tailnet. If this doesn't work you've likely fucked up the previous step and should check it again.

- From the UDM Pro, attempt to ping a device within the tailnet. If you don't get a response, you've got a misconfigured route either on the UDM, or inside of the tailscale container(possibly missing `--accept-routes=true`). Double check the UDM's route table is pointing the tailscale subnet(`100.64.0.0/10`) to the right container IP.

- From another device connected to the UDM pro but not connected to tailscale, attempt to ping a device connected to the tailnet. If this doesn't work but everything else does, it's probably something with your local devices route table and you've got bigger problems. 

Hope this helps.

**Comment by MinisculeGirraffe** [comment]
Oh. One final piece of relevant info I now realize that I haven't mentioned. 

The UDM Pro is acting as a subnet router, exposing the local devices to the tailnet. Any other tailscale devices needs to have `--accept-routes=true` configured on them, otherwise they won't know how to send traffic back to your local network. 

Without it they'll only ever be able to communicate with a tailscale IP address, which everything behind the UDM is not.

**Comment by AKPWebDesign** [comment]
Alright, that's a lot of great info! I really appreciate the time you took here.

I changed my CNI config and startup script to use an IP on my `10.69.0.0/17` network, restarted everything, then went through your troubleshooting steps:

> From the UDM Pro, ping the tailscale containers IP. If no response you've fucked up the CNI config or the interface configuration in the startup script

This worked fine, I can reach the container from the UDM Pro.

> From the container, ping the UDM Pro. This should always work if the previous step works. If it doesn't you've fucked up the same things as above.

Same, pinging the UDM Pro from the container works fine.

> Validate the Tailscale daemon is running inside of the container, and that it's successfully connected. If it's not you've likely fucked up the filesystem mounts when creating the container. Do a docker rm on the container and try again.

Yep, Tailscale daemon is running and connected.

> From within the tailscale container, attempt to ping a device inside of the tailnet. If this doesn't work you've likely fucked up the previous step and should check it again.

This also works. Tailscale container is able to reach devices on both networks (tailnet and UDM network) with no problems.

> From the UDM Pro, attempt to ping a device within the tailnet. If you don't get a response, you've got a misconfigured route either on the UDM, or inside of the tailscale container(possibly missing --accept-routes=true). Double check the UDM's route table is pointing the tailscale subnet(100.64.0.0/10) to the right container IP.

Here's where we run into issues. I'm unable to ping from UDM Pro to the tailnet, despite everything seeming right. I'm starting the tailscale daemon using `--accept-routes=true`, and the UDM routing table looks like it has everything we need:
```
# ip route
default via <redacted> dev eth8 proto static
10.69.0.0/17 dev br0 proto kernel scope link src 10.69.0.1
10.69.56.56 dev br0.mac scope link
100.64.0.0/10 via 10.69.56.56 dev br0.mac # this looks right to me, using the new IP address I assigned the container.
<redacted> dev eth8 proto kernel scope link src <redacted>
```

> From another device connected to the UDM pro but not connected to tailscale, attempt to ping a device connected to the tailnet. If this doesn't work but everything else does, it's probably something with your local devices route table and you've got bigger problems.

This also doesn't work, which I expect given that the UDM Pro can't ping either.


So, I would expect that I can communicate with tailnet from UDM Pro, and it looks like the proper routing is in place. I'm able to ping the tailscale container, and the container is able to reach both networks, but UDM is unable to route through the container for some reason?

Is there anything else you'd try looking at to troubleshoot this? I'm very confused, haha.

**Comment by MinisculeGirraffe** [comment]
Check the route table on the tailscale device you're trying to ping from the UDM Pro. 

Tailscale is supposed to add a route back to your local network via the containers tailscale IP if you've configured the UDM as a subnet router properly.

It sounds like that route is missing, which is why you're seeing the ping fail on the UDM.

also, double check that the subnet  router feature  is enabled on the container from the tailscale gui. That could also prevent the routes from propogating.

**Comment by MinisculeGirraffe** [comment]
Actually I would bet a crisp dollar bill that's your issue.

Validate the Tailscale devices route table. It should have a route to your local subnet (`10.69.0.0/17`) with whatever ip 100.x IP your UDM's tailscale container has. If it doesn't have that, it would mimic what you're describing exactly.

Tailscale will manage these routes automatically, but not by default. You need to enable a flag on the device itself if you want it to do this. 

Tailscale Docs link:
https://tailscale.com/kb/1019/subnets/#step-5-use-your-subnet-routes-from-other-machines

**Comment by AKPWebDesign** [comment]
Yeah, I think you nailed it. It hadn't clicked in my head that the `--accept-routes` was also needed on the other linux-based tailnet device, but now that I've restarted it, everything seems to be working. Thanks again for your time!
